define

# Illegal, just for highlighting test
entity1 sub entity
  relates some-role;

# Illegal, just for highlighting test
attr1 sub attribute
  relates some-role;

# Illegal, just for highlighting test
role1 sub role
  relates some-role;

# Illegal, just for highlighting test
rule1 sub rule
  relates some-role;

relationship1 sub relationship
  relates some-role;
